name: Manual Build Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    defaults:
      run:
        working-directory: ./toXtc_node 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './toXtc_node/package-lock.json'

      - name: Install Dependencies
        run: npm install

      - name: Build Application (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run build-win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Application (Mac)
        if: matrix.os == 'macos-latest'
        run: npm run build-mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: XTC-Master-Converter-${{ matrix.os }}
          path: |
            toXtc_node/dist/*.exe
            toXtc_node/dist/*.dmg
            toXtc_node/dist/*.zip
          retention-days: 7